jobs:
  run-hooks:
    runs-on: ubuntu-latest
    steps:
      - name: Run 'pre-commit' hooks
        uses: dycw/action-pre-commit@latest
        env:
          CI: "1"
        with:
          repos: |-
            dycw/pre-commit-hook-nitpick
            pre-commit/pre-commit-hooks
name: pull-request
"on":
  pull_request:
    branches:
      - master
  schedule:
    - cron: 0 0 * * *
